### ISSUE TITLE
some suggestions: you need to modify the frame_id "/map" to "map", since it would cause some probs

### ISSUE THREAD

**Issue by YixFeng** [url-kaist/patchwork-plusplus-ros#1]
![screenshot-20220727-153057](https://user-images.githubusercontent.com/50914866/181188355-bec7c133-343e-472a-8a7e-0ec988503889.png)

 When I run the 'demo.launch', rviz visualizer cannot output the cloud processed by 'patchworkpp'.
After I change the frame_ids, the system can run!

**Comment by seungjae24** [comment]
Thank you for the suggestion.
Including the code you have commented, I change the related codes and commit it. Thank you :+1:
