### ISSUE TITLE
process has died [pid 12628, exit code -11 cmd ......]

### ISSUE THREAD

**Issue by RenWeiwei123** [url-kaist/patchwork-plusplus-ros#12]
what can we deal with this condition, we use our own lidar data, it can only run about 13 seconds and the process has died

**Comment by RenWeiwei123** [comment]
.

**Comment by RenWeiwei123** [comment]
![Uploading 0451f9ad_8446993.png…]()

**Comment by RenWeiwei123** [comment]
![0451f9ad_8446993](https://user-images.githubusercontent.com/52324829/220044081-9a6dc00d-949a-426e-8082-27ae958f9100.png)

**Comment by willcbaker** [comment]
looks the same as #11

**Comment by RenWeiwei123** [comment]
> looks the same as #11

yes, the same problem

**Comment by seungjae24** [comment]
Hi, @RenWeiwei123.

I've tested Patchwork++ using the same data from #11, but the program didn't died in my case. Therefore, it might be hard to give you the exact solution for this situation. By the way, I will upload the docker image or clarify prerequisite packages as soon as possible. Thank you for sharing your situtation.

**Comment by RenWeiwei123** [comment]
> 

Thank you @seungjae24 , I am puzzled that this problem does not occur when I run this kitti_00_sample.bag

**Comment by seungjae24** [comment]
Do you mean the error occurs only when you use your own data? If yes, could you please share your data? It would be great to test your data for debugging our algorithm. You can contact me by an e-mail written in README.

**Comment by RenWeiwei123** [comment]
> Do you mean the error occurs only when you use your own data? If yes, could you please share your data? It would be great to test your data for debugging our algorithm. You can contact me by an e-mail written in README.

yes,  there is no error when I use kitti_00_sample.bag, and the error occurs only my own bag file, I have sent my bag file to your e-mail ,maybe you can have a try ,thanks a lot

**Comment by RenWeiwei123** [comment]
> Do you mean the error occurs only when you use your own data? If yes, could you please share your data? It would be great to test your data for debugging our algorithm. You can contact me by an e-mail written in README.

hi, @seungjae24 ,  After the code from this line (https://github.com/url-kaist/patchwork-plusplus-ros/blob/master/include/patchworkpp/patchworkpp.hpp#L1024) is modified as:
`         if ((!noise_idxs_.empty()) &&(i == noise_idxs_.front())) {
`
I can run my own data, thanks for your great work!

**Comment by seungjae24** [comment]
Thanks @RenWeiwei123,

It is clear to be failed in some cases. I'll update the code.  Thank you a lot!
