### ISSUE TITLE
low accurancy in mine area

### ISSUE THREAD

**Issue by RenWeiwei123** [url-kaist/patchwork-plusplus-ros#16]
Hello, can I share my bag with you and help me take a look? Thank you very much, I am very confused about this for a long time.

![1](https://user-images.githubusercontent.com/52324829/235084852-421f8ba5-7da3-4282-9c48-c786a93aefad.png)
![2](https://user-images.githubusercontent.com/52324829/235084862-c543f8b0-a5a1-47b9-94de-c7a549813932.png)

**Comment by RenWeiwei123** [comment]
Hello, can I share my bag with you and help me take a look? Thank you very much, I am very confused about this for a long time.

**Comment by LidarPCL** [comment]
The same things happened to me before and it was fixed after modifying a coupe of parameters, such as the flatness threshold. I would suggest to identify the bins first where the false negative points belong to. Then print all the parameters of the specific bin that make the points as non ground, like the elevation, flatness, uprightness and even heading. Once you know what parameters cause the presence of those false negative points, it would be not hard to fix it.

**Comment by RenWeiwei123** [comment]
Thank you very much for your answer, but aren't these flatness thresholds adaptive? If it is adaptive, can it still be modified? I'm not sure if it's possible to add brother's contact information for specific communication, such as WeChat, Twitter, Facebook, or other methods. This issue has been bothering me for a long time, thank you very much！






***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "url-kaist/patchwork-plusplus-ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 下午3:53
***@***.***&gt;;
抄送:&nbsp;"Weiwei ***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [url-kaist/patchwork-plusplus-ros] low accurancy in mine area (Issue #16)





 
The same things happened to me before and it was fixed after modifying a coupe of parameters, such as the flatness threshold. I would suggest to identify the bins first where the false negative points belong to. Then print all the parameters of the specific bin that make the points as non ground, like the elevation, flatness, uprightness and even heading.

**Comment by LidarPCL** [comment]
we can talk more on wechat if you send me your id @RenWeiwei123

**Comment by RenWeiwei123** [comment]
> we can talk more on wechat if you send me your id @RenWeiwei123
thank you, my Wechat ID is:   ren595502183

**Comment by sun421-cloud** [comment]
@RenWeiwei123 您好，请问您调整ok了吗？
