### ISSUE TITLE
High CPU usage when no data input

### ISSUE THREAD

**Issue by cyhasuka** [url-kaist/patchwork-plusplus-ros#18]
Hello, 
Thank you for sharing such a wonderful job. I have a question now, it seems that the program also consumes a large amount of CPU resources without data input (with one CPU core consistently occupying 100%). Why is this? Is there a way to reduce CPU usage?  (CPU: I7-7800k, no data input occupation: 12%, input point cloud scale 45312 pts: 14%)
Thank you and look forward to your answer!

**Comment by cyhasuka** [comment]
Hello, I would like to report the new test progress to you. In this issue, I found that the high CPU resource usage is because in demo.cpp, main function lines 69 to 72, the frequent calls to the "ros::spinOnce();", resulting in the thread lock has been in a cycle of locking and unlocking.Replacing lines 69 to 72 with "ros::spin();" resolves the issue.

**Comment by seungjae24** [comment]
Hi @cyhasuka,

Thank you for finding a great improvement~ I merged your pull request just now. Thank you!
