### ISSUE TITLE
Could you please put rosbag on other platform such as google drive

### ISSUE THREAD

**Issue by FangJingYunner** [url-kaist/patchwork-plusplus-ros#2]
Hi,l use the command wget but always mention `Unable to establish SSL connection.`.Could you please put rosbag on other platform such as google drive?

**Comment by seungjae24** [comment]
Could you try the following command?

`wget https://urserver.kaist.ac.kr/publicdata/patchwork++/kitti_00_sample.bag`

If you download the file successfully, please let me know. I will modify the command for other users.

**Comment by FangJingYunner** [comment]
@seungjae24 the command you give works.l also try directly open https://www.dropbox.com/s/oel7o0azosm0m46/kitti_00_sample.bag on website ,and l can download from it ,it's faster than wget.
