### ISSUE TITLE
What is the version of Open3D

### ISSUE THREAD

**Issue by Zhangxiurui520** [url-kaist/patchwork-plusplus-ros#20]
Hi, what is the version of Open3D, thanks ~

**Comment by seungjae24** [comment]
Hi @Zhangxiurui520,

Thank you for having interest on our work! Actually, this package (patchwork-plusplus-ros) doesn't have any dependency on Open3D. If you are using the other package, [patchwork-plusplus](https://github.com/url-kaist/patchwork-plusplus), the version of Open3D that I used was 0.15.2.

Thank you :)
