### ISSUE TITLE
Any plans to provide support for ROS2? 

### ISSUE THREAD

**Issue by dsakshay** [url-kaist/patchwork-plusplus-ros#23]
I would like to know if you have any plans of creating another branch to provide support for ROS2. It can be very helpful for people trying to use this with ROS2.

**Comment by seungjae24** [comment]
Hi @dsakshay,

We have a plan to provide a version available on ROS2. Unfortunately, we are too busy for other things these days. Please wait for a while, updates for ROS2 will be proceed. By the way, #22 may be helpful for you trying ROS2 version. (I didn't check it carefully yet.) Thank you.

**Comment by dsakshay** [comment]
Oh okay, thanks @seungjae24 #22 uses component node and maybe interesting to look at. Thanks for the help. I shall close the issue for now, you can let me know when the ROS2 version is out.

**Comment by horverno** [comment]
@dsakshay: we have an ROS 2 version, which is the fork of MohamedHussein736's version with dynamic ROS parameters:

https://github.com/jkk-research/patchwork-plusplus-ros 
https://github.com/MohamedHussein736/patchwork-plusplus-ros

@seungjae24:  if you are interested we could create a pull request on a separate branch (but first we will need a new branch for the PR)

**Comment by seungjae24** [comment]
Hi @horverno, we've create a new branch, ROS2, as you requested. Thank a lot for your kind support!
