### ISSUE TITLE
Is there any plan to update this repo?

### ISSUE THREAD

**Issue by Shaoqing26** [url-kaist/patchwork-plusplus-ros#3]
As the Basic repo describes, there had commit [Modify RNR to be available and R-VPF to be correctly operated](https://github.com/url-kaist/patchwork-plusplus/commit/0d430884cbea4c3cfa009cf99a46c4f04ae964e2), is there any play to update to this repo?

**Comment by seungjae24** [comment]
@Shaoqing26 

The update is completed :)

**Comment by Shaoqing26** [comment]
> @Shaoqing26
> 
> The update is completed :)

Thanks~
There also have a personal favor, Could you please provide the code of kitti bin file to rosbag code? I have tried it by myself, but the bag played very lag, and can't find the problems where is. Thanks.

**Comment by seungjae24** [comment]
For the conversion of bin files into rosbag file, I utilized the [semantickitti2bag](https://github.com/amslabtech/semantickitti2bag) repository. It works well :+1:.

**Comment by seungjae24** [comment]
For the conversion of the bin files into rosbag file, I utilized the [semantickitti2bag](https://github.com/amslabtech/semantickitti2bag) repository.
In my case, the provided bag file is played without any lag.

**Comment by Shaoqing26** [comment]
> For the conversion of the bin files into rosbag file, I utilized the [semantickitti2bag](https://github.com/amslabtech/semantickitti2bag) repository. In my case, the provided bag file is played without any lag.

Thanks, I  will try it.
