### ISSUE TITLE
Poor Results on Kitti Sequence 00

### ISSUE THREAD

**Issue by haider8645** [url-kaist/patchwork-plusplus-ros#30]
Hello,

I use the demo.launch without changing any parameters and test on the 00 sequence of kitti dataset. I get results like shown in fig below. These results do not look like the gif on the main page. Any ideas what I am doing wrong?

Best,
Haider

![image](https://github.com/url-kaist/patchwork-plusplus-ros/assets/23505408/f2a979b8-5b08-4852-adbd-03136ddab5c3)

**Comment by haider8645** [comment]
Some false positives on the lexus example bag given with the ros2 version

![image](https://github.com/url-kaist/patchwork-plusplus-ros/assets/23505408/9ca9b93f-c05f-4b26-8a3b-7fbab03e2236)

**Comment by seungjae24** [comment]
Hi @haider8645, I guess that you are trying demo in ROS2 branch.
I recommend you to follow the master branch to duplicate the result same as demo gif.
Parameters on ROS2 version are different from ROS1 version, which are not employed to make gif on main page.

**Comment by haider8645** [comment]
Hey @seungjae24  Thanks for the feedback.

I am comparing the algos in ros2 so need to use that :/

I updated now the params on ros2 version to same as ros1 and the results are better. There are still some false negative ground points close to the vehicle. Is that expected or further parameter tuning is needed?
![kitti_00_4541_pw](https://github.com/url-kaist/patchwork-plusplus-ros/assets/23505408/d988f8ee-d84a-43bf-8457-1e365c24491f)

**Comment by seungjae24** [comment]
If you want more accurate result, you can try fine-tuning parameters such as sizes of zones or thresholds for estimating ground points.
