### ISSUE TITLE
Apply to other multi-beam lidar sensors

### ISSUE THREAD

**Issue by xiaobrnbrn** [url-kaist/patchwork-plusplus-ros#4]
Thanks a lot for sharing your excellent work! If I want to test this project with our own lidar sensors (such as robosense 128-beams rs-ruby lidar), what params need to be adjusted? I found the param settings in the config folder, and in the yaml file, **sensor_height** should be reset according to our platform, are there any other parameters that need to be adjusted? Looking forword to your reply.

**Comment by seungjae24** [comment]
Hi! Thank you for having interest in our work.

Actually, you did well as you set appropriate `sensor_height` value.

Additionally, I can suggest you to modify `max_r` and `min_r` parameters, which will be varied on your setting.
- `max_r` : the maximum radius of area; points with bigger radius than `max_r` value will be treated as non-ground.
- `min_r` : the minimum radius of area; points with smaller radius than `min_r` value will be treated as non-ground.

I don't think that other parameters need to be adjusted significantly. But, if you have any trouble to use Patchwork++ with your own sensor configuration, please let me know.

**Comment by xiaobrnbrn** [comment]
Thanks a lot!

**Comment by xiaobrnbrn** [comment]
> Hi! Thank you for having interest in our work.
> 
> Actually, you did well as you set appropriate `sensor_height` value.
> 
> Additionally, I can suggest you to modify `max_r` and `min_r` parameters, which will be varied on your setting.
> - `max_r` : the maximum radius of area; points with bigger radius than `max_r` value will be treated as non-ground.
> - `min_r` : the minimum radius of area; points with smaller radius than `min_r` value will be treated as non-ground.
> 
> I don't think that other parameters need to be adjusted significantly. But, if you have any trouble to use Patchwork++ with your own sensor configuration, please let me know.

Thanks a lot!
