### ISSUE TITLE
low accurancy

### ISSUE THREAD

**Issue by xovobobo** [url-kaist/patchwork-plusplus-ros#5]
Hello. Looks like this package is not correctly recognized ground in mountains
![Screenshot from 2022-11-04 22-25-07](https://user-images.githubusercontent.com/55924064/200038255-c31c12ff-db9f-40b1-932c-56f4bfb48013.png)

**Comment by seungjae24** [comment]
Hi @xovobobo. Thank you for sharing your segmentation result!

I can't be sure which is the exact problem of your situation. However, I can suggest you to visualize or debug the ground likelihood estimation results by visualizing the polygons representing the ground likelihood estimation result, and then find out the problem of your situation. It might be helpful to try different numbers of the rings/sectors of concentric zone model depending on your specific sensor configuration. Also , if there are multiple planar grounds in a single patch, it might be hard to estimate the ground. I hope it helps your situation. Thank you!
