### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by lr-1998-dy** [url-kaist/patchwork-plusplus-ros#9]
Why the sum of ground points and non-ground points obtained using patchwork-plusplus-rosis not equal to the original point cloud,but patchwork-plusplus has not this problem?

**Comment by seungjae24** [comment]
Hi @lr-1998-dy !

Thank you for catching a bug! Actually, some points were not considered as non-ground points in previous codes.
I fixed it and checked that a sum of ground and non-ground points is same with a number of points in input cloud.
You can check the fixed version at the below link. It is updated on the master branch. Thank you for finding it :)

https://github.com/url-kaist/patchwork-plusplus-ros/tree/4844f2e72e17e86dcedec6512322c6cee96b79aa
